name = "academy-api"
main = "src/worker.ts"
compatibility_date = "2026-09-04"
compatibility_flags = ["nodejs_compat"]
account_id = "64ce0da1d6bde1c338aa1eed69626c73"
workers_dev = true

[vars]
CLOUDFLARE_WORKER = "1"
NODE_ENV = "production"
PORT = "5000"

[limits]
cpu_ms = 30000

[alias]
"iconv-lite" = "./src/iconv-stub.js"
"pg-cloudflare" = "./node_modules/pg-cloudflare/dist/index.js"
